### ISSUE TITLE
Update jackson-databind to 2.13.2.1+

### ISSUE THREAD

**Issue by rohansinha** [fortify-ps/fortify-client-api#21]
com.fasterxml.jackson:jackson-bom:2.13.2 has the same vulnerability reported as 2.13.1. Should ideally update to 2.13.2.1 or 2.13.2.2

https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

**Comment by rsenden** [comment]
Thanks for the tip! I got confused by the version numbering scheme; in other places, 2.13.2 would usually be a synonym for the latest 2.13.2.x version. For jackson-bom they even used yet another scheme, using a date suffix. 

Anyway, I've now released fortify-client-api version 6.1.5, which uses jackson-bom version 2.13.2.20220328 (may take some minutes to show up on Maven Central).
