### ISSUE TITLE
The token end point got changed from /auth/obtain_token to /tokens. 

### ISSUE THREAD

**Issue by anilkumar1998** [fortify-ps/fortify-client-api#3]
https://github.com/fortify-ps/fortify-client-api/blob/7e1168807dabbe72802e1eba6d60249ec6105d38/client-api-ssc/src/main/lombok/com/fortify/client/ssc/connection/SSCTokenFactoryUserCredentials.java#L72

**Comment by rsenden** [comment]
- Endpoint has been updated in commit https://github.com/fortify-ps/fortify-client-api/commit/f70a1e6567f06722bfaca00588d3bdf1dfa4d594
- Added functionality for setting token description
- Added functionality for revoking the token when closing the connection
